# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DHVideoDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'AFNetworking'
  pod 'YYKit'
  pod 'OpenUDID'
  pod 'MBProgressHUD'
  pod 'FMDB'
  pod 'Toast'
  pod 'MJExtension'
  pod 'XZKeychainItemWrapper'
  pod 'Godzippa'
  pod 'SDWebImage','~> 3.8.2'

  # Pods for DHVideoDemo

  target 'DHVideoDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
